### ISSUE TITLE
Models missing

### ISSUE THREAD

**Issue by wfzyx** [coldAmphibian/Defense-of-the-Legends#18]
Someone else is having the same problem?

![image](https://cloud.githubusercontent.com/assets/5880370/8764258/b5324f66-2da3-11e5-9284-fba387126b1c.png)

**Comment by Zarthbenn** [comment]
looks like a texture problem, is the .vmat there?

**Comment by coldAmphibian** [comment]
I'll fix it

**Comment by coldAmphibian** [comment]
Seems like certain models are messed, I tried making a new vmdl from the original fbx, still broken

**Comment by wfzyx** [comment]
I've removed unused compiled files some commits ago, but I don't think is correlate in any way with this problem.

**Comment by coldAmphibian** [comment]
![image](https://cloud.githubusercontent.com/assets/8411784/8804279/d27136ba-300e-11e5-81a1-264181cc2fc3.png)
Nah, it wasn't your fault. I just had to reconnect all the textures in the model editor. All fixed now. I'm loving whoever programmed Leona. 

Could someone please check if it worked for them?

**Comment by wn-mitch** [comment]
Some models are def broken, I can't load the mundo base skin

**Comment by Zarthbenn** [comment]
i think thats because he is not actually imported yet, I can get on that and upload it today

**Comment by wn-mitch** [comment]
I mean I can't load him in the RAF loader haha, the .dds throws an error everytime. I was able to pull the TPA skin and will have a commit ready today or tomorrow hopefully

**Comment by Zarthbenn** [comment]
ah i see,  did you convert the .dss before adding it to the material editor?

**Comment by wn-mitch** [comment]
I couldn't even extract the .dss

**Comment by Zarthbenn** [comment]
thats strange, are you talking about the base or the tpa skin?

**Comment by coldAmphibian** [comment]
and are you using raftools? I managed to extract the whole LoL archive using RAFTools

**Comment by wfzyx** [comment]
![image](https://cloud.githubusercontent.com/assets/5880370/8818878/c813c4fe-301c-11e5-915d-f18af7f31fec.png)

Ok, someone is making fun of me u.u

@coldAmphibian  halp?

**Comment by coldAmphibian** [comment]
pfft... 
![image](https://cloud.githubusercontent.com/assets/8411784/8828345/fd18dbea-30d4-11e5-904c-3d2b11b07527.png)
fixed

**Comment by wfzyx** [comment]
Why ezreal is so fat/tall ? I reduced his scale on 69a6de4f7b9dcf083bee8ef07faa4f2264c7fd00 but still doesn't look good.

Also why is garen face full of squares?

**Comment by coldAmphibian** [comment]
This is why swordzzz stopped working on his video. I'd scale lux to be the same size as crystal maiden and use her as a reference.

**Comment by Zarthbenn** [comment]
This might sound kind of silly now but have we tried everyone at 1.0 scale? Does it look normal? I only started changing the sizes because I was comparing everyone to sven, but now everyone is kind of all over the place.

**Comment by coldAmphibian** [comment]
eh, that can be fixed relatively easily

**Comment by coldAmphibian** [comment]
![image](https://cloud.githubusercontent.com/assets/8411784/8868957/e32922b4-3221-11e5-82bc-be6f7607d81e.png)

**Comment by wfzyx** [comment]
Archived
